// <auto-generated />
using LaborDay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LaborDay.Migrations
{
    [DbContext(typeof(LaborDayContext))]
    partial class LaborDayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaborDay.Models.Bet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BettorID");

                    b.Property<int>("GolferId");

                    b.Property<bool>("Place");

                    b.Property<bool>("Show");

                    b.Property<bool>("Win");

                    b.HasKey("ID");

                    b.HasIndex("BettorID");

                    b.HasIndex("GolferId");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("LaborDay.Models.Bettor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Bettor");
                });

            modelBuilder.Entity("LaborDay.Models.Golfer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GolferName");

                    b.Property<bool>("Playing");

                    b.HasKey("ID");

                    b.ToTable("Golfer");
                });

            modelBuilder.Entity("LaborDay.Models.TempBet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BettorID");

                    b.Property<int>("GolferId");

                    b.Property<int>("Money");

                    b.Property<bool>("Place");

                    b.Property<bool>("Show");

                    b.Property<bool>("Win");

                    b.HasKey("ID");

                    b.ToTable("TempBet");
                });

            modelBuilder.Entity("LaborDay.Models.Bet", b =>
                {
                    b.HasOne("LaborDay.Models.Bettor", "Bettor")
                        .WithMany("Bets")
                        .HasForeignKey("BettorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LaborDay.Models.Golfer", "Golfer")
                        .WithMany("Bets")
                        .HasForeignKey("GolferId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
